spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

  h2:
    console:
      enabled: false

liquibase:
    changeLog: classpath:db.changelog/db.changelog-master.xml
    contexts: prod

extjsdemo:
  swagger:
    enabled: false